name: Test PR
"on": pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  install-and-test:
    name: 🛠️ Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: 🗜️ Checkout
        uses: actions/checkout@v7

      - name: 🗜️ Setup node version
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: 🗜️ Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: 🛠️ Install
        uses: ./.github/actions/cached-deps

      - name: 🛠️ Clean temporary files
        run: yarn clean

      - name: ✅ Validate
        run: yarn validate

      - name: 🗜️ Install coverage tooling
        run: |
          sudo apt-get update
          sudo apt-get install --yes kcov

      - name: ✅ Generate coverage
        run: yarn coverage

      - name: 📊 Report coverage
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: ./.github/actions/report-pr
        with:
          coverage-file: coverage/merged/kcov-merged/cobertura.xml

      - name: 🛠️ Setup package
        run: yarn script:package-npm

      - name: 🛠️ Copy files to dist
        run: yarn copy-files
